--- 
abstract: Parse and format PostgreSQL dates and times
author: "Claus A. F\xE4rber <perl@faerber.muc.de>"
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DateTime-Format-Pg
no_index: 
  directory: 
    - inc
    - t
requires: 
  DateTime: 0.10
  DateTime::Format::Builder: 0.72
  DateTime::TimeZone: 0.05
version: 0.16
