---
abstract: 'Parse and format PostgreSQL dates and times'
author:
  - 'Daisuke Maki <daisuke@endeworks.jp>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Format-Pg
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  DateTime::Format::Pg:
    file: lib/DateTime/Format/Pg.pm
    version: 0.16009
requires:
  DateTime: 0.10
  DateTime::Format::Builder: 0.72
  DateTime::TimeZone: 0.05
resources:
  bugtracker: https://github.com/lestrrat/DateTime-Format-Pg/issues
  homepage: https://github.com/lestrrat/DateTime-Format-Pg
  repository: git://github.com/lestrrat/DateTime-Format-Pg.git
version: 0.16009
x_contributors:
  - 'Vasily Chekalkin <bacek@bacek.com>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'Daisuke Maki <lestrrat+github@gmail.com>'
